version: '3.5'
services:
  rental-client:
    container_name: rental-client
    image: rental-client
    ports:
      - "80:80"
    logging:
      driver: json-file
      options:
           max-size: "100m"
    depends_on: 
      - rabbitmq
    healthcheck:
      test: exit 0 || exit 1
    restart: always
  rental-inventory:
    container_name: rental-inventory
    image: rental-inventory
    logging:
      driver: json-file
      options:
           max-size: "100m"
    depends_on: 
      - rabbitmq
    healthcheck:
      test: exit 0 || exit 1
    restart: always
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: json-file
      options:
           max-size: "100m"
    healthcheck:
      test: exit 0 || exit 1
    restart: always